// <auto-generated />
using System;
using ArenaSync.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArenaSync.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260422042853_Add_TeamReassignmentRequest")]
    partial class Add_TeamReassignmentRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArenaSync.Web.Models.Attendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Attendees", (string)null);
                });

            modelBuilder.Entity("ArenaSync.Web.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("ArenaSync.Web.Models.LockerRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("LockerRooms", (string)null);
                });

            modelBuilder.Entity("ArenaSync.Web.Models.ParticipatesIn", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.HasKey("TeamId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("ParticipatesIn", (string)null);
                });

            modelBuilder.Entity("ArenaSync.Web.Models.RegistersFor", b =>
                {
                    b.Property<int>("AttendeeId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.HasKey("AttendeeId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("RegistersFor", (string)null);
                });

            modelBuilder.Entity("ArenaSync.Web.Models.SuppliesAt", b =>
                {
                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.HasKey("VendorId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("SuppliesAt", (string)null);
                });

            modelBuilder.Entity("ArenaSync.Web.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("ArenaSync.Web.Models.TeamAssignment", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("LockerId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("TeamId", "EventId", "LockerId");

                    b.HasIndex("LockerId");

                    b.HasIndex("EventId", "LockerId")
                        .IsUnique();

                    b.HasIndex("EventId", "TeamId")
                        .IsUnique();

                    b.ToTable("TeamAssignments", (string)null);
                });

            modelBuilder.Entity("ArenaSync.Web.Models.TeamReassignmentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestedEventId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestedEventId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamReassignmentRequests");
                });

            modelBuilder.Entity("ArenaSync.Web.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Vendors", (string)null);
                });

            modelBuilder.Entity("ArenaSync.Web.Models.VendorAssignment", b =>
                {
                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("BoothId")
                        .HasColumnType("int");

                    b.HasKey("VendorId", "EventId", "BoothId");

                    b.HasIndex("BoothId");

                    b.HasIndex("EventId", "BoothId")
                        .IsUnique();

                    b.HasIndex("EventId", "VendorId")
                        .IsUnique();

                    b.ToTable("VendorAssignments", (string)null);
                });

            modelBuilder.Entity("ArenaSync.Web.Models.VendorBooth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoothNumber")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("VendorBooths", (string)null);
                });

            modelBuilder.Entity("ArenaSync.Web.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Venues", (string)null);
                });

            modelBuilder.Entity("ArenaSync.Web.Models.Event", b =>
                {
                    b.HasOne("ArenaSync.Web.Models.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ArenaSync.Web.Models.LockerRoom", b =>
                {
                    b.HasOne("ArenaSync.Web.Models.Venue", "Venue")
                        .WithMany("LockerRooms")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ArenaSync.Web.Models.ParticipatesIn", b =>
                {
                    b.HasOne("ArenaSync.Web.Models.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArenaSync.Web.Models.Team", "Team")
                        .WithMany("ParticipatesIn")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ArenaSync.Web.Models.RegistersFor", b =>
                {
                    b.HasOne("ArenaSync.Web.Models.Attendee", "Attendee")
                        .WithMany("Registrations")
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArenaSync.Web.Models.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ArenaSync.Web.Models.SuppliesAt", b =>
                {
                    b.HasOne("ArenaSync.Web.Models.Event", "Event")
                        .WithMany("Suppliers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArenaSync.Web.Models.Vendor", "Vendor")
                        .WithMany("SuppliesAt")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ArenaSync.Web.Models.TeamAssignment", b =>
                {
                    b.HasOne("ArenaSync.Web.Models.Event", "Event")
                        .WithMany("Assignments")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArenaSync.Web.Models.LockerRoom", "LockerRoom")
                        .WithMany("Assignments")
                        .HasForeignKey("LockerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArenaSync.Web.Models.Team", "Team")
                        .WithMany("Assignments")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("LockerRoom");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ArenaSync.Web.Models.TeamReassignmentRequest", b =>
                {
                    b.HasOne("ArenaSync.Web.Models.Event", "RequestedEvent")
                        .WithMany()
                        .HasForeignKey("RequestedEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArenaSync.Web.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedEvent");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ArenaSync.Web.Models.VendorAssignment", b =>
                {
                    b.HasOne("ArenaSync.Web.Models.VendorBooth", "Booth")
                        .WithMany("VendorAssignments")
                        .HasForeignKey("BoothId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArenaSync.Web.Models.Event", "Event")
                        .WithMany("VendorAssignments")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArenaSync.Web.Models.Vendor", "Vendor")
                        .WithMany("VendorAssignments")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booth");

                    b.Navigation("Event");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ArenaSync.Web.Models.VendorBooth", b =>
                {
                    b.HasOne("ArenaSync.Web.Models.Venue", "Venue")
                        .WithMany("VendorBooths")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ArenaSync.Web.Models.Attendee", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("ArenaSync.Web.Models.Event", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Participants");

                    b.Navigation("Registrations");

                    b.Navigation("Suppliers");

                    b.Navigation("VendorAssignments");
                });

            modelBuilder.Entity("ArenaSync.Web.Models.LockerRoom", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("ArenaSync.Web.Models.Team", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ParticipatesIn");
                });

            modelBuilder.Entity("ArenaSync.Web.Models.Vendor", b =>
                {
                    b.Navigation("SuppliesAt");

                    b.Navigation("VendorAssignments");
                });

            modelBuilder.Entity("ArenaSync.Web.Models.VendorBooth", b =>
                {
                    b.Navigation("VendorAssignments");
                });

            modelBuilder.Entity("ArenaSync.Web.Models.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("LockerRooms");

                    b.Navigation("VendorBooths");
                });
#pragma warning restore 612, 618
        }
    }
}
